"""Render docs/data-dictionary.md from config/metrics.yaml (the registry is the single source of truth)."""

from __future__ import annotations

from backend.app.registry import load_default_score_config, load_metric_registry
from backend.app.settings import REPO_ROOT


def render() -> str:
    reg = load_metric_registry()
    cfg = load_default_score_config()
    out: list[str] = [
        "# Data dictionary",
        "",
        "_Generated by `make docs` from `config/metrics.yaml`. Do not edit by hand._",
        "",
        "## Sources",
        "",
        "| id | name | publisher | vintage | geographies | notes |",
        "|---|---|---|---|---|---|",
    ]
    for sid, s in reg.sources.items():
        levels = ", ".join(level.value for level in s.geo_levels)
        out.append(
            f"| `{sid}` | [{s.name}]({s.url}) | {s.publisher} | {s.vintage} | {levels} | {s.notes or ''} |"
        )
    out += ["", "## Metrics", ""]
    for pid, pillar in cfg.pillars.items():
        out += [
            f"### {pillar.label} (`{pid}`, default pillar weight {pillar.weight})",
            "",
            "| id | label | unit | direction | default weight | geographies | source | derivation |",
            "|---|---|---|---|---|---|---|---|",
        ]
        for m in reg.metrics:
            if m.pillar != pid:
                continue
            direction = (
                "informational"
                if m.higher_is_better is None
                else ("higher is better" if m.higher_is_better else "lower is better")
            )
            levels = ", ".join(level.value for level in m.geo_levels)
            out.append(
                f"| `{m.id}` | {m.label} | {m.unit} | {direction} | {m.scoring_default} | {levels} "
                f"| `{m.source}` | {m.derivation} |"
            )
        out.append("")
    return "\n".join(out)


def main() -> None:
    target = REPO_ROOT / "docs" / "data-dictionary.md"
    target.write_text(render())
    print(f"wrote {target}")


if __name__ == "__main__":
    main()
