"""HRSA Primary Care Health Professional Shortage Areas (HPSA) -> county flag + max score.

Input: the HPSA "detail" extract (one row per HPSA component: census tract, county subdivision,
single county or facility point), all statuses (Designated / Proposed For Withdrawal / Withdrawn).

Output (county level):
  hpsa_primary_care_flag  1 if any component in the county is active (Designated or Proposed For
                          Withdrawal), else 0. A 0 is emitted for every county present in the file,
                          so non-shortage counties are not "missing" - they are known negatives.
  hpsa_score_max          max HPSA Score (0-25) over the county's active components; NULL when none.
"""

from __future__ import annotations

import logging
from pathlib import Path

import pandas as pd

from backend.app.settings import settings
from pipelines.base import METRIC_COLS, Source, Tidy, download, suppressed_to_null
from pipelines.fips import in_states, pad_fips

log = logging.getLogger("pipelines.hrsa_hpsa")

URL = "https://data.hrsa.gov/DataDownload/DD_Files/BCD_HPSA_FCT_DET_PC.csv"
FILENAME = "BCD_HPSA_FCT_DET_PC.csv"

COL_FIPS = "Common State County FIPS Code"
COL_STATUS = "HPSA Status"
COL_SCORE = "HPSA Score"
COL_DISCIPLINE = "HPSA Discipline Class"
COL_CREATED = "Data Warehouse Record Create Date Text"
USECOLS = [COL_FIPS, COL_STATUS, COL_SCORE, COL_DISCIPLINE, COL_CREATED]

ACTIVE_STATUSES = frozenset({"Designated", "Proposed For Withdrawal"})
ENCODINGS = ("utf-8-sig", "cp1252", "latin-1")


def read_hpsa_csv(path: Path) -> pd.DataFrame:
    """Read the detail file with only the needed columns, tolerating BOM / non-UTF-8 encodings."""
    last: UnicodeDecodeError | None = None
    for enc in ENCODINGS:
        try:
            df = pd.read_csv(path, dtype=str, encoding=enc, usecols=lambda c: c in USECOLS, low_memory=False)
        except UnicodeDecodeError as exc:
            last = exc
            continue
        missing = {COL_FIPS, COL_STATUS, COL_SCORE} - set(df.columns)
        if missing:
            raise ValueError(f"hrsa_hpsa: required columns missing from {path.name}: {sorted(missing)}")
        return df
    raise ValueError(f"hrsa_hpsa: could not decode {path.name}") from last


def file_period(df: pd.DataFrame, fallback: str) -> str:
    """'YYYY-MM' of the extract's record-create date (the file is regenerated by HRSA regularly)."""
    if COL_CREATED not in df.columns:
        return fallback
    stamps = pd.to_datetime(df[COL_CREATED].dropna().unique(), format="%Y/%m/%d", errors="coerce").dropna()
    return stamps.max().strftime("%Y-%m") if len(stamps) else fallback


class HpsaSource(Source):
    source_id = "hrsa_hpsa"
    geo_levels = ("county",)

    def extract(self) -> dict[str, Path]:
        return {"detail": download(URL, settings.raw_dir / self.source_id, FILENAME)}

    def transform(self, raw: dict[str, Path]) -> Tidy:
        df = read_hpsa_csv(raw["detail"])
        if COL_DISCIPLINE in df.columns:
            df = df[df[COL_DISCIPLINE].fillna("Primary Care").str.strip().eq("Primary Care")]
        df = df[df[COL_FIPS].notna()].copy()
        df["geo_id"] = pad_fips(df[COL_FIPS], 5)
        df = df[in_states(df["geo_id"], self.sample)]
        df["active"] = df[COL_STATUS].str.strip().isin(ACTIVE_STATUSES)
        df["score"] = suppressed_to_null(df[COL_SCORE])

        period = file_period(df, self.vintage)
        universe = df["geo_id"].drop_duplicates().sort_values()
        active = df[df["active"]]
        score_max = active.groupby("geo_id")["score"].max()  # NaN if all active scores are suppressed

        flag = pd.DataFrame({"geo_id": universe})
        flag["metric_id"] = "hpsa_primary_care_flag"
        flag["value"] = flag["geo_id"].isin(active["geo_id"]).astype(float)

        score = pd.DataFrame({"geo_id": universe})
        score["metric_id"] = "hpsa_score_max"
        score["value"] = score["geo_id"].map(score_max)

        out = pd.concat([flag, score], ignore_index=True)
        out["geo_level"] = "county"
        out["period"] = period
        log.info(
            "hrsa_hpsa: %d counties in universe, %d flagged active, %d with a score (period %s)",
            len(universe),
            int(flag["value"].sum()),
            int(score["value"].notna().sum()),
            period,
        )
        return Tidy(metric_values=out[METRIC_COLS].reset_index(drop=True))
